### ISSUE TITLE
Python 3.7 - ImportError: cannot import name 'CallableMeta' from 'typing'

### ISSUE THREAD

**Issue by ZhukovGreen** [smarie/python-valid8#24]
Hi, when importing validate8 got an error:
ImportError: cannot import name 'CallableMeta' from 'typing' (/usr/lib/python3.7/typing.py)

It is line 13 in valid8/_typing_inspect.py

**Comment by smarie** [comment]
Hi, thanks for the feedback! It seems that this is a python 3.7 issue - the typing module has maybe changed a bit. I'll have a look into it next week. In the meantime you can have a try with python 3.6

**Comment by ZhukovGreen** [comment]
Thx

**Comment by smarie** [comment]
@ZhukovGreen it should be fixed in the latest version 3.7.3. Could you please confirm ? Thanks in advance!

**Comment by smarie** [comment]
Thanks!
